name: "static analysis checker"
description: 'static code analysis checker for golang'
author: 'grandcolline'
inputs:
  run:
    description: "excute command. [errcheck/fmt/imports/lint/sec/shadow/staticcheck/vet]"
  directory:
    description: "action wroking directory."
    default: "."
  comment:
    description: "send comment to PR if true."
    default: true
  token:
    description: "github token. this is require when comment is true."
  flags:
    description: "add flags"
    default: ""
  ignore-defer:
    description: "if this is true, do not detect 'defer' with error. This is only valid when run is errcheck."
    default: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.run }}
    - ${{ inputs.directory }}
    - ${{ inputs.comment }}
    - ${{ inputs.token }}
    - ${{ inputs.flags }}
    - ${{ inputs.ignore-defer }}
